modules:

  # ------------------------------------------------------
  # HTTP / HTTPS PROBE
  # ------------------------------------------------------
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      follow_redirects: true
      preferred_ip_protocol: "ip4"

  # ------------------------------------------------------
  # PING ICMP PROBE
  # ------------------------------------------------------
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

  # ------------------------------------------------------
  # TCP CONNECT PROBE
  # ------------------------------------------------------
  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"

  # ------------------------------------------------------
  # DNS CHECK
  # ------------------------------------------------------
  dns:
    prober: dns
    timeout: 5s
    dns:
      query_name: "google.com"
      query_type: "A"
      valid_rcodes:
        - NOERROR

  # ------------------------------------------------------
  # HTTP POST CHECK (API)
  # ------------------------------------------------------
  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      fail_if_body_not_matches_regexp:
        - ".*"
      fail_if_not_ssl: false
      preferred_ip_protocol: "ip4"

  # ------------------------------------------------------
  # TLS CERTIFICATE CHECK
  # ------------------------------------------------------
  tls:
    prober: tcp
    timeout: 5s
    tcp:
      tls: true
      tls_config:
        insecure_skip_verify: true

